### ISSUE TITLE
開発サーバーの起動に失敗する

### ISSUE THREAD

**Issue by nishitaku** [angular/angular-ja#717]
`yarn start`すると、以下エラーが発生します。

<details>
  <summary>View error</summary>

```
% yarn start
yarn run v1.22.19
warning ../../package.json: No license field
$ docker-compose up --remove-orphans watch-aio
[+] Running 0/1
 ⠿ watch-aio Error                                                         3.1s
[+] Building 148.9s (18/19)
 => [internal] load build definition from watch.dockerfile                 0.0s
 => => transferring dockerfile: 38B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 34B                                           0.0s
 => [internal] load metadata for docker.io/library/node:16.15.0            1.6s
 => [ 1/18] FROM docker.io/library/node:16.15.0@sha256:59eb4e9d6a344ae116  0.0s
 => [internal] load build context                                         18.8s
 => => transferring context: 495.73MB                                     18.7s
 => CACHED [ 2/18] RUN apt-get update                                      0.0s
 => CACHED [ 3/18] RUN apt-get install -y rsync                            0.0s
 => CACHED [ 4/18] COPY origin /origin/                                    0.0s
 => CACHED [ 5/18] COPY tools/dockerbuild/package.json /                   0.0s
 => CACHED [ 6/18] RUN yarn install --no-lockfile                          0.0s
 => [ 7/18] COPY .git/modules .git/modules/                                1.3s
 => [ 8/18] WORKDIR /origin                                                0.0s
 => [ 9/18] RUN git clean -xdn                                             0.5s
 => [10/18] COPY aio-ja /aio-ja/                                           0.1s
 => [11/18] COPY scripts /scripts/                                         0.0s
 => [12/18] COPY tools/dockerbuild/scripts/apply-localization.mjs tools/d  0.0s
 => [13/18] RUN npx zx apply-localization.mjs                              0.8s
 => ERROR [14/18] RUN npx zx setup-aio.mjs                               125.5s
------
 > [14/18] RUN npx zx setup-aio.mjs:
#0 0.513 $ cd /origin/aio
#0 0.513 $ yarn setup
#0 0.815 yarn run v1.22.17
#0 0.891 $ yarn --cwd .. install && yarn install --frozen-lockfile && yarn ~~check-env && yarn ~~clean-generated && yarn boilerplate:remove
#0 1.236 [1/5] Validating package.json...
#0 1.244 [2/5] Resolving packages...
#0 1.312 warning Resolution field "https-proxy-agent@5.0.1" is incompatible with requested version "https-proxy-agent@5.0.0"
#0 1.544 warning Resolution field "saucelabs@7.1.3" is incompatible with requested version "saucelabs@^1.5.0"
#0 1.545 warning Resolution field "https-proxy-agent@5.0.1" is incompatible with requested version "https-proxy-agent@^2.2.1"
#0 1.548 warning Resolution field "https-proxy-agent@5.0.1" is incompatible with requested version "https-proxy-agent@5.0.0"
#0 1.693 warning Resolution field "saucelabs@7.1.3" is incompatible with requested version "saucelabs@^4.6.3"
#0 1.698 warning Resolution field "https-proxy-agent@5.0.1" is incompatible with requested version "https-proxy-agent@^4.0.0"
#0 1.765 [3/5] Fetching packages...
#0 63.10 [4/5] Linking dependencies...
#0 63.11 warning " > @angular-devkit/build-angular@13.3.6" has unmet peer dependency "@angular/compiler-cli@^13.0.0 || ^13.3.0-rc.0".
#0 63.11 warning " > @angular-devkit/build-angular@13.3.6" has incorrect peer dependency "typescript@>=4.4.3 <4.7".
#0 63.11 warning "@angular-devkit/build-angular > @ngtools/webpack@13.3.6" has unmet peer dependency "@angular/compiler-cli@^13.0.0".
#0 63.11 warning "@angular-devkit/build-angular > @ngtools/webpack@13.3.6" has incorrect peer dependency "typescript@>=4.4.3 <4.7".
#0 63.11 warning " > @angular/animations-12@12.2.13" has unmet peer dependency "@angular/core@12.2.13".
#0 63.11 warning " > @angular/cdk@13.3.7" has unmet peer dependency "@angular/core@^13.0.0 || ^14.0.0-0".
#0 63.11 warning " > @angular/cdk@13.3.7" has unmet peer dependency "@angular/common@^13.0.0 || ^14.0.0-0".
#0 63.11 warning " > @angular/common-12@12.2.13" has unmet peer dependency "@angular/core@12.2.13".
#0 63.11 warning " > @angular/core-12@12.2.13" has unmet peer dependency "zone.js@~0.11.4".
#0 63.11 warning " > @angular/forms-12@12.2.13" has unmet peer dependency "@angular/core@12.2.13".
#0 63.11 warning " > @angular/forms-12@12.2.13" has unmet peer dependency "@angular/common@12.2.13".
#0 63.11 warning " > @angular/forms-12@12.2.13" has unmet peer dependency "@angular/platform-browser@12.2.13".
#0 63.11 warning " > @angular/material@13.3.7" has unmet peer dependency "@angular/animations@^13.0.0 || ^14.0.0-0".
#0 63.11 warning " > @angular/material@13.3.7" has unmet peer dependency "@angular/core@^13.0.0 || ^14.0.0-0".
#0 63.11 warning " > @angular/material@13.3.7" has unmet peer dependency "@angular/common@^13.0.0 || ^14.0.0-0".
#0 63.11 warning " > @angular/material@13.3.7" has unmet peer dependency "@angular/forms@^13.0.0 || ^14.0.0-0".
#0 63.11 warning " > @angular/material@13.3.7" has unmet peer dependency "@angular/platform-browser@^13.0.0 || ^14.0.0-0".
#0 63.11 warning " > @angular/platform-browser-12@12.2.13" has unmet peer dependency "@angular/core@12.2.13".
#0 63.11 warning " > @angular/platform-browser-12@12.2.13" has unmet peer dependency "@angular/common@12.2.13".
#0 63.11 warning " > @angular/platform-browser-dynamic-12@12.2.13" has unmet peer dependency "@angular/core@12.2.13".
#0 63.11 warning " > @angular/platform-browser-dynamic-12@12.2.13" has unmet peer dependency "@angular/common@12.2.13".
#0 63.11 warning " > @angular/platform-browser-dynamic-12@12.2.13" has unmet peer dependency "@angular/compiler@12.2.13".
#0 63.11 warning " > @angular/platform-browser-dynamic-12@12.2.13" has unmet peer dependency "@angular/platform-browser@12.2.13".
#0 63.11 warning " > @angular/platform-server-12@12.2.13" has unmet peer dependency "@angular/animations@12.2.13".
#0 63.11 warning " > @angular/platform-server-12@12.2.13" has unmet peer dependency "@angular/common@12.2.13".
#0 63.11 warning " > @angular/platform-server-12@12.2.13" has unmet peer dependency "@angular/compiler@12.2.13".
#0 63.11 warning " > @angular/platform-server-12@12.2.13" has unmet peer dependency "@angular/core@12.2.13".
#0 63.11 warning " > @angular/platform-server-12@12.2.13" has unmet peer dependency "@angular/platform-browser@12.2.13".
#0 63.11 warning " > @angular/platform-server-12@12.2.13" has unmet peer dependency "@angular/platform-browser-dynamic@12.2.13".
#0 63.11 warning " > @angular/router-12@12.2.13" has unmet peer dependency "@angular/core@12.2.13".
#0 63.11 warning " > @angular/router-12@12.2.13" has unmet peer dependency "@angular/common@12.2.13".
#0 63.11 warning " > @angular/router-12@12.2.13" has unmet peer dependency "@angular/platform-browser@12.2.13".
#0 63.11 warning " > @bazel/concatjs@5.4.2" has unmet peer dependency "karma-junit-reporter@>=2.0.0".
#0 63.11 warning " > @bazel/terser@5.4.2" has incorrect peer dependency "terser@>=4.0.0 <5.9.0".
#0 63.11 warning " > ngx-flamegraph@0.0.11" has unmet peer dependency "@angular/common@^9.0.0".
#0 63.11 warning " > ngx-flamegraph@0.0.11" has unmet peer dependency "@angular/core@^9.0.0".
#0 63.11 warning " > tsickle@0.38.1" has incorrect peer dependency "typescript@~3.8.2".
#0 63.11 warning "@angular/dev-infra-private > @angular-devkit/build-angular@14.0.0-rc.1" has unmet peer dependency "@angular/compiler-cli@^14.0.0 || ^14.0.0-rc".
#0 63.11 warning "@angular/dev-infra-private > @bazel/concatjs@5.5.0" has unmet peer dependency "karma-junit-reporter@>=2.0.0".
#0 63.11 warning "@angular/dev-infra-private > @bazel/terser@5.5.0" has incorrect peer dependency "terser@>=4.0.0 <5.9.0".
#0 63.11 warning "@angular/dev-infra-private > @angular-devkit/build-angular > @ngtools/webpack@14.0.0-rc.1" has unmet peer dependency "@angular/compiler-cli@^14.0.0 || ^14.0.0-rc".
#0 63.11 warning "@angular/dev-infra-private > @angular/benchpress > @angular/core@14.0.0" has unmet peer dependency "zone.js@~0.11.4".
#0 63.11 warning " > tslint-eslint-rules@5.4.0" has incorrect peer dependency "tslint@^5.0.0".
#0 63.11 warning " > tslint-eslint-rules@5.4.0" has incorrect peer dependency "typescript@^2.2.0 || ^3.0.0".
#0 63.15 warning Workspaces can only be enabled in private projects.
#0 96.81 [5/5] Building fresh packages...
#0 120.5 $ node scripts/webdriver-manager-update.js && node --preserve-symlinks --preserve-symlinks-main ./tools/postinstall-patches.js
#0 120.8 $ /origin/node_modules/.bin/webdriver-manager update --gecko=false --standalone=false --versions.chrome 93.0.4577.63
#0 121.0 [05:34:15] I/file_manager - creating folder /origin/node_modules/webdriver-manager/selenium
#0 121.0 [05:34:15] I/config_source - curl -o/origin/node_modules/webdriver-manager/selenium/chrome-response.xml https://chromedriver.storage.googleapis.com/
#0 121.5 [05:34:15] E/downloader - options.uri is a required argument
#0 121.5 [05:34:15] I/update - chromedriver: file exists /origin/node_modules/webdriver-manager/selenium/chromedriver_93.0.4577.63.zip
#0 121.5 [05:34:15] I/update - chromedriver: unzipping chromedriver_93.0.4577.63.zip
#0 121.5 /origin/node_modules/webdriver-manager/built/lib/cmds/update.js:232
#0 121.5             throw new Error(`Invalid filename: ${path.resolve(outputDir, fileName)}`);
#0 121.5                   ^
#0 121.5
#0 121.5 Error: Invalid filename: /origin/node_modules/webdriver-manager/selenium/chromedriver_93.0.4577.63.zip
#0 121.5     at unzip (/origin/node_modules/webdriver-manager/built/lib/cmds/update.js:232:19)
#0 121.5     at /origin/node_modules/webdriver-manager/built/lib/cmds/update.js:205:13
#0 121.5     at processTicksAndRejections (node:internal/process/task_queues:96:5)
#0 121.5     at async Promise.all (index 0)
#0 121.5 error Command failed with exit code 1.
#0 121.5 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#0 121.5 [webdriver-manager-update.js] Call to 'yarn webdriver-manager update --gecko=false --standalone=false --versions.chrome 93.0.4577.63' failed with error code 1
#0 121.5
#0 121.5 Trying again (attempt 1 of 3)...
#0 121.5
#0 121.6 $ /origin/node_modules/.bin/webdriver-manager update --gecko=false --standalone=false --versions.chrome 93.0.4577.63
#0 121.9 [05:34:16] E/downloader - options.uri is a required argument
#0 121.9 [05:34:16] I/update - chromedriver: file exists /origin/node_modules/webdriver-manager/selenium/chromedriver_93.0.4577.63.zip
#0 121.9 [05:34:16] I/update - chromedriver: unzipping chromedriver_93.0.4577.63.zip
#0 121.9 /origin/node_modules/webdriver-manager/built/lib/cmds/update.js:232
#0 121.9             throw new Error(`Invalid filename: ${path.resolve(outputDir, fileName)}`);
#0 121.9                   ^
#0 121.9
#0 121.9 Error: Invalid filename: /origin/node_modules/webdriver-manager/selenium/chromedriver_93.0.4577.63.zip
#0 121.9     at unzip (/origin/node_modules/webdriver-manager/built/lib/cmds/update.js:232:19)
#0 121.9     at /origin/node_modules/webdriver-manager/built/lib/cmds/update.js:205:13
#0 121.9     at async Promise.all (index 0)
#0 121.9 error Command failed with exit code 1.
#0 121.9 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#0 121.9 [webdriver-manager-update.js] Call to 'yarn webdriver-manager update --gecko=false --standalone=false --versions.chrome 93.0.4577.63' failed with error code 1
#0 121.9
#0 121.9 Trying again (attempt 2 of 3)...
#0 121.9
#0 122.0 $ /origin/node_modules/.bin/webdriver-manager update --gecko=false --standalone=false --versions.chrome 93.0.4577.63
#0 122.3 [05:34:16] E/downloader - options.uri is a required argument
#0 122.3 [05:34:16] I/update - chromedriver: file exists /origin/node_modules/webdriver-manager/selenium/chromedriver_93.0.4577.63.zip
#0 122.3 [05:34:16] I/update - chromedriver: unzipping chromedriver_93.0.4577.63.zip
#0 122.3 /origin/node_modules/webdriver-manager/built/lib/cmds/update.js:232
#0 122.3             throw new Error(`Invalid filename: ${path.resolve(outputDir, fileName)}`);
#0 122.3                   ^
#0 122.3
#0 122.3 Error: Invalid filename: /origin/node_modules/webdriver-manager/selenium/chromedriver_93.0.4577.63.zip
#0 122.3     at unzip (/origin/node_modules/webdriver-manager/built/lib/cmds/update.js:232:19)
#0 122.3     at /origin/node_modules/webdriver-manager/built/lib/cmds/update.js:205:13
#0 122.3     at async Promise.all (index 0)
#0 122.3 error Command failed with exit code 1.
#0 122.3 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#0 122.3 [webdriver-manager-update.js] Call to 'yarn webdriver-manager update --gecko=false --standalone=false --versions.chrome 93.0.4577.63' failed with error code 1
#0 122.3
#0 122.3 Trying again (attempt 3 of 3)...
#0 122.3
#0 122.4 $ /origin/node_modules/.bin/webdriver-manager update --gecko=false --standalone=false --versions.chrome 93.0.4577.63
#0 122.7 [05:34:16] E/downloader - options.uri is a required argument
#0 122.7 [05:34:16] I/update - chromedriver: file exists /origin/node_modules/webdriver-manager/selenium/chromedriver_93.0.4577.63.zip
#0 122.7 [05:34:16] I/update - chromedriver: unzipping chromedriver_93.0.4577.63.zip
#0 122.7 /origin/node_modules/webdriver-manager/built/lib/cmds/update.js:232
#0 122.7             throw new Error(`Invalid filename: ${path.resolve(outputDir, fileName)}`);
#0 122.7                   ^
#0 122.7
#0 122.7 Error: Invalid filename: /origin/node_modules/webdriver-manager/selenium/chromedriver_93.0.4577.63.zip
#0 122.7     at unzip (/origin/node_modules/webdriver-manager/built/lib/cmds/update.js:232:19)
#0 122.7     at /origin/node_modules/webdriver-manager/built/lib/cmds/update.js:205:13
#0 122.7     at async Promise.all (index 0)
#0 122.7 error Command failed with exit code 1.
#0 122.7 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#0 122.7 [webdriver-manager-update.js] Call to 'yarn webdriver-manager update --gecko=false --standalone=false --versions.chrome 93.0.4577.63' failed with error code 1
#0 122.7 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
#0 122.7 error Command failed with exit code 1.
#0 124.2 error Command failed with exit code 1.
#0 124.2 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#0 124.4 Error: warning Resolution field "https-proxy-agent@5.0.1" is incompatible with requested version "https-proxy-agent@5.0.0"
#0 124.4 warning Resolution field "saucelabs@7.1.3" is incompatible with requested version "saucelabs@^1.5.0"
#0 124.4 warning Resolution field "https-proxy-agent@5.0.1" is incompatible with requested version "https-proxy-agent@^2.2.1"
#0 124.4 warning Resolution field "https-proxy-agent@5.0.1" is incompatible with requested version "https-proxy-agent@5.0.0"
#0 124.4 warning Resolution field "saucelabs@7.1.3" is incompatible with requested version "saucelabs@^4.6.3"
#0 124.4 warning Resolution field "https-proxy-agent@5.0.1" is incompatible with requested version "https-proxy-agent@^4.0.0"
#0 124.4 warning " > @angular-devkit/build-angular@13.3.6" has unmet peer dependency "@angular/compiler-cli@^13.0.0 || ^13.3.0-rc.0".
#0 124.4 warning " > @angular-devkit/build-angular@13.3.6" has incorrect peer dependency "typescript@>=4.4.3 <4.7".
#0 124.4 warning "@angular-devkit/build-angular > @ngtools/webpack@13.3.6" has unmet peer dependency "@angular/compiler-cli@^13.0.0".
#0 124.4 warning "@angular-devkit/build-angular > @ngtools/webpack@13.3.6" has incorrect peer dependency "typescript@>=4.4.3 <4.7".
#0 124.4 warning " > @angular/animations-12@12.2.13" has unmet peer dependency "@angular/core@12.2.13".
#0 124.4 warning " > @angular/cdk@13.3.7" has unmet peer dependency "@angular/core@^13.0.0 || ^14.0.0-0".
#0 124.4 warning " > @angular/cdk@13.3.7" has unmet peer dependency "@angular/common@^13.0.0 || ^14.0.0-0".
#0 124.4 warning " > @angular/common-12@12.2.13" has unmet peer dependency "@angular/core@12.2.13".
#0 124.4 warning " > @angular/core-12@12.2.13" has unmet peer dependency "zone.js@~0.11.4".
#0 124.4 warning " > @angular/forms-12@12.2.13" has unmet peer dependency "@angular/core@12.2.13".
#0 124.4 warning " > @angular/forms-12@12.2.13" has unmet peer dependency "@angular/common@12.2.13".
#0 124.4 warning " > @angular/forms-12@12.2.13" has unmet peer dependency "@angular/platform-browser@12.2.13".
#0 124.4 warning " > @angular/material@13.3.7" has unmet peer dependency "@angular/animations@^13.0.0 || ^14.0.0-0".
#0 124.4 warning " > @angular/material@13.3.7" has unmet peer dependency "@angular/core@^13.0.0 || ^14.0.0-0".
#0 124.4 warning " > @angular/material@13.3.7" has unmet peer dependency "@angular/common@^13.0.0 || ^14.0.0-0".
#0 124.4 warning " > @angular/material@13.3.7" has unmet peer dependency "@angular/forms@^13.0.0 || ^14.0.0-0".
#0 124.4 warning " > @angular/material@13.3.7" has unmet peer dependency "@angular/platform-browser@^13.0.0 || ^14.0.0-0".
#0 124.4 warning " > @angular/platform-browser-12@12.2.13" has unmet peer dependency "@angular/core@12.2.13".
#0 124.4 warning " > @angular/platform-browser-12@12.2.13" has unmet peer dependency "@angular/common@12.2.13".
#0 124.4 warning " > @angular/platform-browser-dynamic-12@12.2.13" has unmet peer dependency "@angular/core@12.2.13".
#0 124.4 warning " > @angular/platform-browser-dynamic-12@12.2.13" has unmet peer dependency "@angular/common@12.2.13".
#0 124.4 warning " > @angular/platform-browser-dynamic-12@12.2.13" has unmet peer dependency "@angular/compiler@12.2.13".
#0 124.4 warning " > @angular/platform-browser-dynamic-12@12.2.13" has unmet peer dependency "@angular/platform-browser@12.2.13".
#0 124.4 warning " > @angular/platform-server-12@12.2.13" has unmet peer dependency "@angular/animations@12.2.13".
#0 124.4 warning " > @angular/platform-server-12@12.2.13" has unmet peer dependency "@angular/common@12.2.13".
#0 124.4 warning " > @angular/platform-server-12@12.2.13" has unmet peer dependency "@angular/compiler@12.2.13".
#0 124.4 warning " > @angular/platform-server-12@12.2.13" has unmet peer dependency "@angular/core@12.2.13".
#0 124.4 warning " > @angular/platform-server-12@12.2.13" has unmet peer dependency "@angular/platform-browser@12.2.13".
#0 124.4 warning " > @angular/platform-server-12@12.2.13" has unmet peer dependency "@angular/platform-browser-dynamic@12.2.13".
#0 124.4 warning " > @angular/router-12@12.2.13" has unmet peer dependency "@angular/core@12.2.13".
#0 124.4 warning " > @angular/router-12@12.2.13" has unmet peer dependency "@angular/common@12.2.13".
#0 124.4 warning " > @angular/router-12@12.2.13" has unmet peer dependency "@angular/platform-browser@12.2.13".
#0 124.4 warning " > @bazel/concatjs@5.4.2" has unmet peer dependency "karma-junit-reporter@>=2.0.0".
#0 124.4 warning " > @bazel/terser@5.4.2" has incorrect peer dependency "terser@>=4.0.0 <5.9.0".
#0 124.4 warning " > ngx-flamegraph@0.0.11" has unmet peer dependency "@angular/common@^9.0.0".
#0 124.4 warning " > ngx-flamegraph@0.0.11" has unmet peer dependency "@angular/core@^9.0.0".
#0 124.4 warning " > tsickle@0.38.1" has incorrect peer dependency "typescript@~3.8.2".
#0 124.4 warning "@angular/dev-infra-private > @angular-devkit/build-angular@14.0.0-rc.1" has unmet peer dependency "@angular/compiler-cli@^14.0.0 || ^14.0.0-rc".
#0 124.4 warning "@angular/dev-infra-private > @bazel/concatjs@5.5.0" has unmet peer dependency "karma-junit-reporter@>=2.0.0".
#0 124.4 warning "@angular/dev-infra-private > @bazel/terser@5.5.0" has incorrect peer dependency "terser@>=4.0.0 <5.9.0".
#0 124.4 warning "@angular/dev-infra-private > @angular-devkit/build-angular > @ngtools/webpack@14.0.0-rc.1" has unmet peer dependency "@angular/compiler-cli@^14.0.0 || ^14.0.0-rc".
#0 124.4 warning "@angular/dev-infra-private > @angular/benchpress > @angular/core@14.0.0" has unmet peer dependency "zone.js@~0.11.4".
#0 124.4 warning " > tslint-eslint-rules@5.4.0" has incorrect peer dependency "tslint@^5.0.0".
#0 124.4 warning " > tslint-eslint-rules@5.4.0" has incorrect peer dependency "typescript@^2.2.0 || ^3.0.0".
#0 124.4 warning Workspaces can only be enabled in private projects.
#0 124.4 /origin/node_modules/webdriver-manager/built/lib/cmds/update.js:232
#0 124.4             throw new Error(`Invalid filename: ${path.resolve(outputDir, fileName)}`);
#0 124.4                   ^
#0 124.4
#0 124.4 Error: Invalid filename: /origin/node_modules/webdriver-manager/selenium/chromedriver_93.0.4577.63.zip
#0 124.4     at unzip (/origin/node_modules/webdriver-manager/built/lib/cmds/update.js:232:19)
#0 124.4     at /origin/node_modules/webdriver-manager/built/lib/cmds/update.js:205:13
#0 124.4     at processTicksAndRejections (node:internal/process/task_queues:96:5)
#0 124.4     at async Promise.all (index 0)
#0 124.4 error Command failed with exit code 1.
#0 124.4 [webdriver-manager-update.js] Call to 'yarn webdriver-manager update --gecko=false --standalone=false --versions.chrome 93.0.4577.63' failed with error code 1
#0 124.4 /origin/node_modules/webdriver-manager/built/lib/cmds/update.js:232
#0 124.4             throw new Error(`Invalid filename: ${path.resolve(outputDir, fileName)}`);
#0 124.4                   ^
#0 124.4
#0 124.4 Error: Invalid filename: /origin/node_modules/webdriver-manager/selenium/chromedriver_93.0.4577.63.zip
#0 124.4     at unzip (/origin/node_modules/webdriver-manager/built/lib/cmds/update.js:232:19)
#0 124.4     at /origin/node_modules/webdriver-manager/built/lib/cmds/update.js:205:13
#0 124.4     at async Promise.all (index 0)
#0 124.4 error Command failed with exit code 1.
#0 124.4 [webdriver-manager-update.js] Call to 'yarn webdriver-manager update --gecko=false --standalone=false --versions.chrome 93.0.4577.63' failed with error code 1
#0 124.4 /origin/node_modules/webdriver-manager/built/lib/cmds/update.js:232
#0 124.4             throw new Error(`Invalid filename: ${path.resolve(outputDir, fileName)}`);
#0 124.4                   ^
#0 124.4
#0 124.4 Error: Invalid filename: /origin/node_modules/webdriver-manager/selenium/chromedriver_93.0.4577.63.zip
#0 124.4     at unzip (/origin/node_modules/webdriver-manager/built/lib/cmds/update.js:232:19)
#0 124.4     at /origin/node_modules/webdriver-manager/built/lib/cmds/update.js:205:13
#0 124.4     at async Promise.all (index 0)
#0 124.4 error Command failed with exit code 1.
#0 124.4 [webdriver-manager-update.js] Call to 'yarn webdriver-manager update --gecko=false --standalone=false --versions.chrome 93.0.4577.63' failed with error code 1
#0 124.4 /origin/node_modules/webdriver-manager/built/lib/cmds/update.js:232
#0 124.4             throw new Error(`Invalid filename: ${path.resolve(outputDir, fileName)}`);
#0 124.4                   ^
#0 124.4
#0 124.4 Error: Invalid filename: /origin/node_modules/webdriver-manager/selenium/chromedriver_93.0.4577.63.zip
#0 124.4     at unzip (/origin/node_modules/webdriver-manager/built/lib/cmds/update.js:232:19)
#0 124.4     at /origin/node_modules/webdriver-manager/built/lib/cmds/update.js:205:13
#0 124.4     at async Promise.all (index 0)
#0 124.4 error Command failed with exit code 1.
#0 124.4 [webdriver-manager-update.js] Call to 'yarn webdriver-manager update --gecko=false --standalone=false --versions.chrome 93.0.4577.63' failed with error code 1
#0 124.4 error Command failed with exit code 1.
#0 124.4 error Command failed with exit code 1.
#0 124.4     at file:///setup-aio.mjs:4:8
------
failed to solve: executor failed running [/bin/sh -c npx zx setup-aio.mjs]: exit code: 1
error Command failed with exit code 17.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
</details>

**Comment by rch850** [comment]
私も同じ現象が発生していて困っています。M1 Mac であれば、おそらくこの issue に引っかかっていると思われます。解決策はまだ見つかっていません。

https://github.com/angular/webdriver-manager/issues/510

**Comment by lacolaco** [comment]
同じく自分のローカルでも発生しました。ふだんCIでしかビルドしていなかったので気づかなかった... 
いまのところ解決策思いついてないです。

**Comment by lacolaco** [comment]
いまさらですが、Dockerを使わずM1 Macで直接ならば angular/angular レポジトリの aioプロジェクトはビルドできるんですね 

もともとはtmpディレクトリにaio-jaとoriginのファイルを両方コピーしてビルドする仕組みで、それをやめて仮想fsとしてdocker化しましたが、もとに戻してもいいのかもしれません...

**Comment by lacolaco** [comment]
dockerをやめたことで解決しました！
